name: Building Recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1
  DEVICE: j7elte
  DT_LINK: https://github.com/OrangeFoxRecovery/device_samsung_j7elte.git
  DT_PATH: device/samsung/j7elte
  CT_LINK: https://github.com/OrangeFoxRecovery/device_samsung_exynos7580-common.git
  CT_PATH: device/samsung/exynos7580-common
  KERNEL_LINK: https://github.com/OrangeFoxRecovery/kernel_samsung_exynos7580-common.git
  KERNEL_PATH: kernel/samsung/exynos7580-common
  MISC_LINK: https://github.com/OrangeFoxRecovery/avatar.git
  MISC_PATH: misc
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Initializing environment
         run: |
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
            git config --global user.name "Sushrut1101"
            git config --global user.email "guptasushrut@gmail.com"         
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
            sudo -E apt-get clean 
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Syncing Recovery Source, Device Trees and the Kernel Trees...
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -j4 --force-sync
             cd build
             wget https://gitlab.com/OrangeFox/sync/-/raw/master/patches/patch-manifest-fox_8.1.diff
             patch -p1 < patch-manifest-fox_8.1.diff
             cd -
             rm -rf bootable/recovery
             rm -rf vendor/recovery
             git clone https://gitlab.com/OrangeFox/bootable/Recovery.git bootable/recovery
             git clone https://gitlab.com/OrangeFox/vendor/recovery.git vendor/recovery
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             git clone $CT_LINK --depth=1 --single-branch $CT_PATH
             git clone $KERNEL_LINK --depth=1 --single-branch $KERNEL_PATH
             git clone $MISC_LINK --depth=1 --single-branch $MISC_PATH
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh &&lunch omni_$DEVICE-eng &&export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET
             
       - uses: actions/upload-artifact@v2
         with:
          name: recoveryzip
          path: work/out/target/product/*/*.zip

       - uses: actions/upload-artifact@v2
         with:
          name: recoveryimage
          path: work/out/target/product/*/*.img
